name: Deploy HOK QQBot QQ Service

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    if: |
      !contains(github.event.head_commit.message, '[skip ci]')
    steps:
      - name: Kill Old Nonebot
        run: |
          # 如果 8080 端口没有进程，避免 kill 报错导致工作流中断，加了 || true
          lsof -i:8080 | awk '/python/ {print $2}' | uniq | xargs -r kill || true

      - name: Pull Without Touching History
        run: |
          cd /QQBot/NBot/
          git fetch origin main

          git reset --mixed origin/main
          git restore --source=origin/main --worktree -- . ':(exclude)data/history'

      - name: Restart Nonebot
        run: |
          cd /QQBot/NBot
          chmod +x deploy_runner.sh
          nohup ./deploy_runner.sh &
